-- ============================================
-- Main Database Initialization
-- Hinweis: User wurde bereits durch 01-create-user.sql erstellt
-- ============================================

-- Connect as the syncuser
CONNECT syncuser/syncpass123@XEPDB1;

-- Create the SyncItems table
CREATE TABLE SyncItems (
    Id VARCHAR2(36) PRIMARY KEY,
    Name VARCHAR2(255) NOT NULL,
    Description VARCHAR2(1000),
    CreatedAt TIMESTAMP NOT NULL,
    ModifiedAt TIMESTAMP NOT NULL,
    IsDeleted NUMBER(1) DEFAULT 0 NOT NULL,
    Version NUMBER DEFAULT 1 NOT NULL
);

-- Create indexes
CREATE INDEX idx_syncitems_modified ON SyncItems(ModifiedAt);
CREATE INDEX idx_syncitems_deleted ON SyncItems(IsDeleted);

-- Insert sample data
INSERT INTO SyncItems (Id, Name, Description, CreatedAt, ModifiedAt, IsDeleted, Version)
VALUES (SYS_GUID(), 'Sample Item 1', 'This is a sample item created during initialization', SYSTIMESTAMP, SYSTIMESTAMP, 0, 1);

INSERT INTO SyncItems (Id, Name, Description, CreatedAt, ModifiedAt, IsDeleted, Version)
VALUES (SYS_GUID(), 'Sample Item 2', 'Another sample item', SYSTIMESTAMP, SYSTIMESTAMP, 0, 1);

-- Create USERS table
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    EMAIL VARCHAR2(200),
    ROLE VARCHAR2(50) DEFAULT 'USER' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Create DEVICES table
CREATE TABLE DEVICES (
    DEVICE_ID VARCHAR2(100) PRIMARY KEY,
    DEVICE_NAME VARCHAR2(200),
    USER_ID NUMBER,
    DEVICE_TYPE VARCHAR2(50),
    REGISTERED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_SEEN TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_DEVICES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create index on USER_ID for faster lookups
CREATE INDEX IDX_DEVICES_USER ON DEVICES(USER_ID);

-- Create DEVICE_PERMISSIONS table
CREATE TABLE DEVICE_PERMISSIONS (
    PERMISSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID VARCHAR2(100) NOT NULL,
    ENTITY_TYPE VARCHAR2(50) NOT NULL,
    ENTITY_ID NUMBER,
    PERMISSION_TYPE VARCHAR2(20) NOT NULL,
    GRANTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    GRANTED_BY NUMBER,
    CONSTRAINT FK_DEVICE_PERM FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES(DEVICE_ID),
    CONSTRAINT FK_GRANTED_BY FOREIGN KEY (GRANTED_BY) REFERENCES USERS(USER_ID)
);

-- Create index for faster permission lookups
CREATE INDEX IDX_DEVICE_PERMISSIONS ON DEVICE_PERMISSIONS(DEVICE_ID, ENTITY_TYPE);

-- Create USER_DATA_SCOPE table (for future use)
CREATE TABLE USER_DATA_SCOPE (
    SCOPE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ENTITY_TYPE VARCHAR2(50) NOT NULL,
    FILTER_COLUMN VARCHAR2(100),
    FILTER_VALUE VARCHAR2(200),
    CONSTRAINT FK_USER_SCOPE FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Insert test users
INSERT INTO USERS (USERNAME, EMAIL, ROLE) VALUES ('admin', 'admin@example.com', 'ADMIN');
INSERT INTO USERS (USERNAME, EMAIL, ROLE) VALUES ('user1', 'user1@example.com', 'USER');
INSERT INTO USERS (USERNAME, EMAIL, ROLE) VALUES ('viewer', 'viewer@example.com', 'VIEWER');

COMMIT;

EXIT;
