-- Connect to the PDB and create USERS table
CONNECT syncuser/syncpass@XEPDB1;

-- Create USERS table
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    EMAIL VARCHAR2(200),
    ROLE VARCHAR2(50) DEFAULT 'USER' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Insert test users
INSERT INTO USERS (USERNAME, EMAIL, ROLE) VALUES ('admin', 'admin@example.com', 'ADMIN');
INSERT INTO USERS (USERNAME, EMAIL, ROLE) VALUES ('user1', 'user1@example.com', 'USER');
INSERT INTO USERS (USERNAME, EMAIL, ROLE) VALUES ('viewer', 'viewer@example.com', 'VIEWER');

COMMIT;
