-- Connect to the PDB and create DEVICES table
CONNECT syncuser/syncpass@XEPDB1;

-- Create DEVICES table
CREATE TABLE DEVICES (
    DEVICE_ID VARCHAR2(100) PRIMARY KEY,
    DEVICE_NAME VARCHAR2(200),
    USER_ID NUMBER,
    DEVICE_TYPE VARCHAR2(50),
    REGISTERED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_SEEN TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_DEVICES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create index on USER_ID for faster lookups
CREATE INDEX IDX_DEVICES_USER ON DEVICES(USER_ID);

COMMIT;
