-- Connect to the PDB and create DEVICE_PERMISSIONS table
CONNECT syncuser/syncpass@XEPDB1;

-- Create DEVICE_PERMISSIONS table
CREATE TABLE DEVICE_PERMISSIONS (
    PERMISSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID VARCHAR2(100) NOT NULL,
    ENTITY_TYPE VARCHAR2(50) NOT NULL,
    ENTITY_ID NUMBER,
    PERMISSION_TYPE VARCHAR2(20) NOT NULL,
    GRANTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    GRANTED_BY NUMBER,
    CONSTRAINT FK_DEVICE_PERM FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES(DEVICE_ID),
    CONSTRAINT FK_GRANTED_BY FOREIGN KEY (GRANTED_BY) REFERENCES USERS(USER_ID)
);

-- Create index for faster permission lookups
CREATE INDEX IDX_DEVICE_PERMISSIONS ON DEVICE_PERMISSIONS(DEVICE_ID, ENTITY_TYPE);

COMMIT;
