-- Connect to the PDB and create USER_DATA_SCOPE table
CONNECT syncuser/syncpass@XEPDB1;

-- Create USER_DATA_SCOPE table (for future use)
CREATE TABLE USER_DATA_SCOPE (
    SCOPE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ENTITY_TYPE VARCHAR2(50) NOT NULL,
    FILTER_COLUMN VARCHAR2(100),
    FILTER_VALUE VARCHAR2(200),
    CONSTRAINT FK_USER_SCOPE FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

COMMIT;
